// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bar: string;
  controls: string;
  icon: string;
  input: string;
  search: string;
  sort: string;
}
declare const cssExports: CssExports;
export default cssExports;
