// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  description: string;
  label: string;
  list: string;
  row: string;
  switch: string;
  text: string;
  thumb: string;
}
declare const cssExports: CssExports;
export default cssExports;
