// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  roles: string;
  search: string;
  searchIcon: string;
  searchInput: string;
  stack: string;
  user: string;
  username: string;
}
declare const cssExports: CssExports;
export default cssExports;
