// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  body: string;
  cancel: string;
  fields: string;
  indicator: string;
  layout: string;
  marker: string;
  panel: string;
  panelDescription: string;
  panelHead: string;
  panelPosition: string;
  panelTitle: string;
  position: string;
  progress: string;
  review: string;
  reviewGroup: string;
  reviewHead: string;
  reviewInvalid: string;
  reviewList: string;
  reviewRow: string;
  reviewTitle: string;
  step: string;
  stepTitle: string;
  steps: string;
}
declare const cssExports: CssExports;
export default cssExports;
