// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  ambient: string;
  card: string;
  frame: string;
  hero: string;
  image: string;
  round: string;
  row: string;
  square: string;
}
declare const cssExports: CssExports;
export default cssExports;
