// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  art: string;
  backdrop: string;
  content: string;
  eyebrow: string;
  hero: string;
  rise: string;
  subtitle: string;
  text: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
