// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  kind: string;
  link: string;
  meta: string;
  row: string;
  secondary: string;
  text: string;
  title: string;
  trailing: string;
}
declare const cssExports: CssExports;
export default cssExports;
