// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  art: string;
  card: string;
  kind: string;
  link: string;
  secondary: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
