// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  action: string;
  head: string;
  shelf: string;
  title: string;
  track: string;
}
declare const cssExports: CssExports;
export default cssExports;
