// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  action: string;
  bar: string;
  sentinel: string;
  title: string;
  visible: string;
}
declare const cssExports: CssExports;
export default cssExports;
