// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  details: string;
  footer: string;
  metaLine: string;
  price: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
