// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  links: string;
  past: string;
  section: string;
  summary: string;
  tags: string;
}
declare const cssExports: CssExports;
export default cssExports;
