// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  detail: string;
  header: string;
  list: string;
  panel: string;
  panelTitle: string;
  requestActions: string;
  requestCard: string;
  requestTitle: string;
  requestTitleRow: string;
  stateAccepted: string;
  statePending: string;
  stateRejected: string;
}
declare const cssExports: CssExports;
export default cssExports;
