// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  item: string;
  line: string;
  link: string;
  text: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
