// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  detail: string;
  header: string;
  panel: string;
  panelTitle: string;
}
declare const cssExports: CssExports;
export default cssExports;
