// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  head: string;
  subtitle: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
