// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  empty: string;
  end: string;
  frame: string;
  hideOnPhone: string;
  linked: string;
  primary: string;
  row: string;
  rowLink: string;
  table: string;
}
declare const cssExports: CssExports;
export default cssExports;
