// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  section: string;
  sectionHead: string;
  sectionLink: string;
  sectionTitle: string;
  stats: string;
}
declare const cssExports: CssExports;
export default cssExports;
