// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  body: string;
  chips: string;
  description: string;
  empty: string;
  image: string;
  text: string;
}
declare const cssExports: CssExports;
export default cssExports;
