// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  empty: string;
  item: string;
  list: string;
  main: string;
  meta: string;
  target: string;
  title: string;
  titleRow: string;
}
declare const cssExports: CssExports;
export default cssExports;
