// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  chip: string;
  danger: string;
  info: string;
  neutral: string;
  success: string;
  warning: string;
}
declare const cssExports: CssExports;
export default cssExports;
