// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  box: string;
  chip: string;
  chips: string;
  input: string;
  remove: string;
}
declare const cssExports: CssExports;
export default cssExports;
