// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  list: string;
  panel: string;
  sections: string;
  tab: string;
  tabs: string;
}
declare const cssExports: CssExports;
export default cssExports;
