// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  body: string;
  item: string;
  meta: string;
  secondary: string;
  text: string;
  title: string;
  top: string;
}
declare const cssExports: CssExports;
export default cssExports;
