// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  avatar: string;
  email: string;
  fieldLabel: string;
  fieldValue: string;
  fields: string;
  header: string;
  identity: string;
  name: string;
}
declare const cssExports: CssExports;
export default cssExports;
