// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  button: string;
  eventTitle: string;
  label: string;
  layer: string;
  meta: string;
  moving: string;
  placeName: string;
  placeOnly: string;
  settled: string;
}
declare const cssExports: CssExports;
export default cssExports;
