// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  body: string;
  card: string;
  close: string;
  dateChip: string;
  footer: string;
  image: string;
  imageLink: string;
  imageTint: string;
  kindLink: string;
  media: string;
  placeChip: string;
  placeRow: string;
  tagChip: string;
  tags: string;
  title: string;
  titleClamp: string;
  titleNowrap: string;
  titleRow: string;
  viewChip: string;
  wide: string;
}
declare const cssExports: CssExports;
export default cssExports;
