// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  above: string;
  below: string;
  button: string;
  group: string;
  item: string;
  recenter: string;
  recenterActive: string;
  root: string;
  tooltip: string;
}
declare const cssExports: CssExports;
export default cssExports;
