// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  body: string;
  content: string;
  main: string;
  shell: string;
}
declare const cssExports: CssExports;
export default cssExports;
