// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  backdrop: string;
  close: string;
  current: string;
  domain: string;
  domainDescription: string;
  domainLabel: string;
  drawer: string;
  drawerContent: string;
  drawerHeader: string;
  drawerTitle: string;
  footer: string;
  link: string;
  list: string;
  nav: string;
  sidebar: string;
  viewport: string;
}
declare const cssExports: CssExports;
export default cssExports;
