// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  badge: string;
  brand: string;
  header: string;
  logo: string;
  menuButton: string;
  skip: string;
  slash: string;
  wordmark: string;
}
declare const cssExports: CssExports;
export default cssExports;
