// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  crumb: string;
  crumbLink: string;
  crumbs: string;
  description: string;
  head: string;
  heading: string;
  page: string;
  separator: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
