// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  chevron: string;
  icon: string;
  name: string;
  trigger: string;
}
declare const cssExports: CssExports;
export default cssExports;
