// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  check: string;
  item: string;
  itemHint: string;
  itemIcon: string;
  itemText: string;
  label: string;
  popup: string;
  positioner: string;
  separator: string;
}
declare const cssExports: CssExports;
export default cssExports;
