// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  hint: string;
  icon: string;
  label: string;
  top: string;
  value: string;
}
declare const cssExports: CssExports;
export default cssExports;
