// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  avatar: string;
  email: string;
  name: string;
  trigger: string;
  who: string;
}
declare const cssExports: CssExports;
export default cssExports;
