// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  main: string;
  overlay: string;
  overlayCard: string;
}
declare const cssExports: CssExports;
export default cssExports;
