// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  detail: string;
  main: string;
  text: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
