// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  code: string;
  content: string;
  dot: string;
  glow1: string;
  glow2: string;
  main: string;
  pulse: string;
  tag: string;
  text: string;
}
declare const cssExports: CssExports;
export default cssExports;
