// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  link: string;
  list: string;
  notice: string;
}
declare const cssExports: CssExports;
export default cssExports;
