/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlace"];
        put: operations["updatePlace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{id}/invitations/{eventPlanId}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["respondToPlaceInvitation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPerformer"];
        put: operations["updatePerformer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performers/{id}/invitations/{eventPlanId}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["respondToPerformerInvitation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/likes/places/{placeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["isPlaceLiked"];
        put: operations["likePlace"];
        post?: never;
        delete: operations["unlikePlace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/likes/performers/{performerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["isPerformerLiked"];
        put: operations["likePerformer"];
        post?: never;
        delete: operations["unlikePerformer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/likes/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["isEventLiked"];
        put: operations["likeEvent"];
        post?: never;
        delete: operations["unlikeEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-plan/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEventPlan"];
        put: operations["updateEventPlan"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-plan/{id}/invite-place/{placeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["invitePlace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["grant"];
        post?: never;
        delete: operations["revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlaces"];
        put?: never;
        post: operations["createPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPerformers"];
        put?: never;
        post: operations["createPerformer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createEventPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-plan/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishEventPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-plan/{id}/add-lineup-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addLineupInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlaceInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/owned-places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOwnedPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/liked-places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLikedPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performers/{id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPerformerInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performers/owned-performers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOwnedPerformers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/performers/liked-performers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLikedPerformers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/place": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEventPlace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/upcoming-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUpcomingEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/owned-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOwnedEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/liked-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLikedEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-plan/{id}/lineup-invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLineupInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-plan/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlacesToInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-plan/owned-event-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOwnedEventPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-plan/{id}/lineup-invitation/{performerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteLineupInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GeoPointDto: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        LinkDto: {
            /** @enum {string} */
            type: "INSTAGRAM" | "FACEBOOK" | "TWITTER" | "REDDIT" | "WEBSITE";
            url: string;
        };
        PlaceCreateDto: {
            name: string;
            location: components["schemas"]["GeoPointDto"];
            address: string;
            city: string;
            description?: string | null;
            image?: string | null;
            tags?: string[] | null;
            links?: components["schemas"]["LinkDto"][] | null;
        };
        PlaceDto: {
            /** Format: uuid */
            id: string;
            name: string;
            location: components["schemas"]["GeoPointDto"];
            address: string;
            city: string;
            description?: string | null;
            image?: string | null;
            tags: string[];
            links: components["schemas"]["LinkDto"][];
        };
        PerformerCreateDto: {
            name: string;
            genre: string;
            bio: string;
            image?: string | null;
            links?: components["schemas"]["LinkDto"][] | null;
        };
        PerformerDto: {
            /** Format: uuid */
            id: string;
            name: string;
            genre: string;
            bio: string;
            image?: string | null;
            links: components["schemas"]["LinkDto"][];
        };
        LikeStatusDto: {
            liked: boolean;
        };
        EventPlanCreateDto: {
            title: string;
            description: string;
            /** Format: date-time */
            startDateTime: string;
            /** Format: date-time */
            endDateTime: string;
            image?: string | null;
            price?: string | null;
            /** @enum {string} */
            kind: "DISCO" | "TECHNO" | "FESTIVAL" | "JAZZ" | "ALTER" | "HOME" | "PUB";
            links?: components["schemas"]["LinkDto"][] | null;
        };
        EventPlanDto: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            /** Format: date-time */
            startDateTime: string;
            /** Format: date-time */
            endDateTime: string;
            image?: string | null;
            price?: string | null;
            /** @enum {string} */
            kind: "DISCO" | "TECHNO" | "FESTIVAL" | "JAZZ" | "ALTER" | "HOME" | "PUB";
            links: components["schemas"]["LinkDto"][];
            placeInvitation?: components["schemas"]["EventPlanPlaceInvitationDto"] | null;
            lineupInvitations: components["schemas"]["EventPlanLineupInvitationDto"][];
        };
        EventPlanLineupInvitationDto: {
            /** @enum {string} */
            state: "PENDING" | "ACCEPTED" | "REJECTED";
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            performer: components["schemas"]["PerformerDto"];
        };
        EventPlanPlaceInvitationDto: {
            /** @enum {string} */
            state: "PENDING" | "ACCEPTED" | "REJECTED";
            place: components["schemas"]["PlaceDto"];
        };
        EventPlanLineupInvitationCreatePayloadDto: {
            /** Format: uuid */
            performerId: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
        };
        SearchHitDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "PLACE" | "EVENT" | "PERFORMER";
            title: string;
            subtitle: string;
            image?: string | null;
            /** Format: date-time */
            nextEventStart?: string | null;
            /** Format: uuid */
            placeId?: string | null;
        };
        SearchResponseDto: {
            query: string;
            hits: components["schemas"]["SearchHitDto"][];
        };
        EventPlanPlaceInvitationWithDateDto: {
            /** Format: uuid */
            eventPlanId: string;
            /** @enum {string} */
            state: "PENDING" | "ACCEPTED" | "REJECTED";
            title: string;
            /** Format: date-time */
            startDateTime: string;
            /** Format: date-time */
            endDateTime: string;
        };
        PlaceAdminListItemDto: {
            /** Format: uuid */
            id: string;
            name: string;
            address: string;
            city: string;
        };
        EventPlanLineupInvitationForPerformerDto: {
            /** Format: uuid */
            eventPlanId: string;
            eventPlanTitle: string;
            /** @enum {string} */
            state: "PENDING" | "ACCEPTED" | "REJECTED";
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            performer: components["schemas"]["PerformerDto"];
        };
        PerformerAdminListItemDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        EventDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: uuid */
            placeId: string;
            description: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            image?: string | null;
            lineupItems: components["schemas"]["EventLineupItemDto"][];
            price?: string | null;
            /** @enum {string} */
            kind: "DISCO" | "TECHNO" | "FESTIVAL" | "JAZZ" | "ALTER" | "HOME" | "PUB";
            links: components["schemas"]["LinkDto"][];
        };
        EventLineupItemDto: {
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            performer: components["schemas"]["PerformerDto"];
        };
        PlaceUpcomingEventDto: {
            /** Format: uuid */
            placeId: string;
            /** Format: uuid */
            eventId: string;
            title: string;
            image?: string | null;
            /** Format: date-time */
            start: string;
            /** @enum {string} */
            kind: "DISCO" | "TECHNO" | "FESTIVAL" | "JAZZ" | "ALTER" | "HOME" | "PUB";
        };
        EventAdminListItemDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            placeName: string;
        };
        LikedEventsGroupedDto: {
            upcoming: components["schemas"]["EventDto"][];
            past: components["schemas"]["EventDto"][];
        };
        EventPlanAdminListItemDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            startDateTime: string;
            /** Format: date-time */
            endDateTime: string;
        };
        AdminUserDto: {
            /** Format: uuid */
            id: string;
            username: string;
            email?: string | null;
            firstName?: string | null;
            lastName?: string | null;
            enabled: boolean;
            roles: string[];
        };
        AdminUserPageDto: {
            items: components["schemas"]["AdminUserDto"][];
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDto"];
                };
            };
        };
    };
    updatePlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceCreateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDto"];
                };
            };
        };
    };
    respondToPlaceInvitation: {
        parameters: {
            query: {
                /** @description accept or reject */
                state: string;
            };
            header?: never;
            path: {
                id: string;
                eventPlanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPerformer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformerDto"];
                };
            };
        };
    };
    updatePerformer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerformerCreateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformerDto"];
                };
            };
        };
    };
    respondToPerformerInvitation: {
        parameters: {
            query: {
                /** @description accept or reject */
                state: string;
            };
            header?: never;
            path: {
                id: string;
                eventPlanId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    isPlaceLiked: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatusDto"];
                };
            };
        };
    };
    likePlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatusDto"];
                };
            };
        };
    };
    unlikePlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatusDto"];
                };
            };
        };
    };
    isPerformerLiked: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                performerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatusDto"];
                };
            };
        };
    };
    likePerformer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                performerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatusDto"];
                };
            };
        };
    };
    unlikePerformer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                performerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatusDto"];
                };
            };
        };
    };
    isEventLiked: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatusDto"];
                };
            };
        };
    };
    likeEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatusDto"];
                };
            };
        };
    };
    unlikeEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeStatusDto"];
                };
            };
        };
    };
    getEventPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPlanDto"];
                };
            };
        };
    };
    updateEventPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPlanCreateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPlanDto"];
                };
            };
        };
    };
    invitePlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    grant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                /** @description A manager role. */
                role: "event_organizer_user" | "place_manager_user" | "performer_manager_user";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                /** @description A manager role. */
                role: "event_organizer_user" | "place_manager_user" | "performer_manager_user";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPlaces: {
        parameters: {
            query?: {
                /**
                 * @description Only places inside minLon,minLat,maxLon,maxLat
                 * @example 18.9,47.3,19.3,47.7
                 */
                bbox?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDto"][];
                };
            };
        };
    };
    createPlace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceCreateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDto"];
                };
            };
        };
    };
    getPerformers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformerDto"][];
                };
            };
        };
    };
    createPerformer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerformerCreateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformerDto"];
                };
            };
        };
    };
    createEventPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPlanCreateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPlanDto"];
                };
            };
        };
    };
    publishEventPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addLineupInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPlanLineupInvitationCreatePayloadDto"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponseDto"];
                };
            };
        };
    };
    getPlaceInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPlanPlaceInvitationWithDateDto"][];
                };
            };
        };
    };
    getOwnedPlaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceAdminListItemDto"][];
                };
            };
        };
    };
    getLikedPlaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDto"][];
                };
            };
        };
    };
    getPerformerInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPlanLineupInvitationForPerformerDto"][];
                };
            };
        };
    };
    getOwnedPerformers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformerAdminListItemDto"][];
                };
            };
        };
    };
    getLikedPerformers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformerDto"][];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                placeId?: string;
                performerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"][];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"];
                };
            };
        };
    };
    getEventPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDto"];
                };
            };
        };
    };
    getUpcomingEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceUpcomingEventDto"][];
                };
            };
        };
    };
    getOwnedEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAdminListItemDto"][];
                };
            };
        };
    };
    getLikedEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikedEventsGroupedDto"];
                };
            };
        };
    };
    getLineupInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPlanLineupInvitationDto"][];
                };
            };
        };
    };
    getPlacesToInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceAdminListItemDto"][];
                };
            };
        };
    };
    getOwnedEventPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPlanAdminListItemDto"][];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description Part of the username, email, first or last name; blank lists everyone. */
                q?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPageDto"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDto"];
                };
            };
        };
    };
    deleteLineupInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                performerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
