// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bar: string;
  block: string;
  button: string;
  danger: string;
  ghost: string;
  md: string;
  primary: string;
  secondary: string;
  sm: string;
  success: string;
}
declare const cssExports: CssExports;
export default cssExports;
