// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  chip: string;
  pressed: string;
  row: string;
}
declare const cssExports: CssExports;
export default cssExports;
