// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  banner: string;
  credit: string;
  text: string;
  title: string;
  wrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
