// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  image: string;
  lg: string;
  md: string;
  sm: string;
}
declare const cssExports: CssExports;
export default cssExports;
