// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  clamped: string;
  faded: string;
  text: string;
  toggle: string;
}
declare const cssExports: CssExports;
export default cssExports;
