// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  control: string;
  error: string;
  field: string;
  form: string;
  grid2: string;
  hint: string;
  label: string;
  labelRow: string;
  prefix: string;
  prefixed: string;
}
declare const cssExports: CssExports;
export default cssExports;
