// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pill: string;
  primary: string;
  secondary: string;
}
declare const cssExports: CssExports;
export default cssExports;
