// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  glyph: string;
  link: string;
  list: string;
}
declare const cssExports: CssExports;
export default cssExports;
