// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  empty: string;
  error: string;
  spin: string;
  spinner: string;
  state: string;
}
declare const cssExports: CssExports;
export default cssExports;
