// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  lead: string;
  link: string;
  muted: string;
  pageTitle: string;
  sectionTitle: string;
}
declare const cssExports: CssExports;
export default cssExports;
