// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  column: string;
  columns: string;
  past: string;
  pastList: string;
  summary: string;
}
declare const cssExports: CssExports;
export default cssExports;
