// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  checklist: string;
  description: string;
  details: string;
  facts: string;
  grid: string;
  kind: string;
  links: string;
  main: string;
}
declare const cssExports: CssExports;
export default cssExports;
