// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  empty: string;
  form: string;
  formTitle: string;
  hint: string;
  item: string;
  list: string;
  name: string;
  slot: string;
  who: string;
}
declare const cssExports: CssExports;
export default cssExports;
