// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  addRow: string;
  editor: string;
  item: string;
  itemFooter: string;
  list: string;
}
declare const cssExports: CssExports;
export default cssExports;
