// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  hint: string;
  icon: string;
  item: string;
  label: string;
  list: string;
  note: string;
  status: string;
  text: string;
}
declare const cssExports: CssExports;
export default cssExports;
