// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  address: string;
  chevron: string;
  collapsible: string;
  current: string;
  icon: string;
  name: string;
  panel: string;
  state: string;
  text: string;
  trigger: string;
}
declare const cssExports: CssExports;
export default cssExports;
