// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  description: string;
  links: string;
  metaLine: string;
  price: string;
  title: string;
  titleRow: string;
}
declare const cssExports: CssExports;
export default cssExports;
