// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  links: string;
  price: string;
  section: string;
}
declare const cssExports: CssExports;
export default cssExports;
