// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  genre: string;
  item: string;
  list: string;
  performer: string;
  time: string;
  top: string;
}
declare const cssExports: CssExports;
export default cssExports;
