// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bio: string;
  eventLink: string;
  events: string;
  links: string;
  metaLine: string;
  title: string;
  titleRow: string;
}
declare const cssExports: CssExports;
export default cssExports;
