// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  back: string;
  content: string;
  main: string;
  tab: string;
  tabActive: string;
  tabs: string;
}
declare const cssExports: CssExports;
export default cssExports;
