// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bottomBar: string;
  bottomTheme: string;
  bottomWrapper: string;
  brand: string;
  brandFull: string;
  brandShort: string;
  explore: string;
  lead: string;
  search: string;
  topActions: string;
  topBar: string;
  topWrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
