// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  anonymous: string;
  desktop: string;
  desktopNav: string;
  item: string;
  mobile: string;
  mobileNav: string;
  nav: string;
}
declare const cssExports: CssExports;
export default cssExports;
