// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  back: string;
  content: string;
  footer: string;
  main: string;
  wide: string;
}
declare const cssExports: CssExports;
export default cssExports;
