// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  box: string;
  disabled: string;
  dropdown: string;
  iconButton: string;
  input: string;
  item: string;
  itemDate: string;
  itemMain: string;
  itemSubtitle: string;
  itemText: string;
  itemTitle: string;
  itemTitleRow: string;
  noResults: string;
  root: string;
  roundActive: string;
  roundButton: string;
  roundMuted: string;
  thumb: string;
  thumbImage: string;
  thumbLetter: string;
  typeEvent: string;
  typePerformer: string;
  typePill: string;
  typePlace: string;
  viewButton: string;
}
declare const cssExports: CssExports;
export default cssExports;
