// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cancelButton: string;
  confirm: string;
  confirmActions: string;
  confirmButton: string;
  confirmText: string;
  confirmTitle: string;
  error: string;
  info: string;
  success: string;
  toast: string;
  toastIn: string;
  viewport: string;
}
declare const cssExports: CssExports;
export default cssExports;
